repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    # Git style
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: no-commit-to-branch
      args: [--branch, master]

    # Common errors
    - id: end-of-file-fixer
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
      exclude: CHANGELOG.md
    - id: check-merge-conflict

- repo: local
  hooks:
    - id: terraform-docs
      name: terraform-docs
      language: docker_image
      entry: quay.io/terraform-docs/terraform-docs:0.17.0  # or, change latest to pin to a specific version
      # args: ["ARGS", "TO PASS", "INCLUDING PATH"]          # e.g. ["--output-file", "README.md", "./mymodule/path"]
      args: ["--output-file", "README.md"]
      pass_filenames: false
